plugins {
    id 'com.android.application'
}

android {
    namespace 'com.scanguard.infowedge'
    compileSdk 34

    defaultConfig {
        applicationId 'com.scanguard.infowedge'
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
